### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by fabioknoedt** [sascha/SSCWhatsAppActivity#3]
Hi @sascha! Thanks for sharing the code!
Can I ask why the WhatsApp icons are white and not green as the official one?

**Comment by sascha** [comment]
I actually don't remember. I think with iOS 7 the icon appeared in the lower section, together with the "Copy", "Print", etc. icons. Please feel free to submit a pull request with the green icon and I will gladly merge it.

**Comment by ntsh** [comment]
Hi @sascha , this change made the whole icon in UIActivityViewController as grey. 

This question on stackoverflow explains the issue. http://stackoverflow.com/questions/25817265/ios-8-custom-uiactivity-image-black-background-color

**Comment by fabioknoedt** [comment]
Hi @ntsh, actually I did the change and proposed the pull request.
Which iOS version are you talking about? In iOS 8 for me it looks perfect.

**Comment by ntsh** [comment]
I tested it on iOS 7

**Comment by fabioknoedt** [comment]
OK, I will review it and upload new images on Tuesday. Sorry, I have to ask my designer to do it.
Sorry about that, mate.

**Comment by ntsh** [comment]
Thanks @fabioknoedt  

You could use the older versions of the icon for iOS 6 and iOS 7 (changed in https://github.com/sascha/SSCWhatsAppActivity/commit/5175c4187f70da923fe4129bcc67ce1b8c98d1df)

For now v1.2 of this library works well for me.

**Comment by sascha** [comment]
Hi @ntsh, sorry about that. Fixed in https://github.com/sascha/SSCWhatsAppActivity/commit/7928d1e4f18c14bdc928334b49821e9c2a4892ad and pushed 1.2.2 to CocoaPods
