### ISSUE TITLE
Can not run in iOS8

### ISSUE THREAD

**Issue by tocute** [sascha/SSCWhatsAppActivity#5]
Very thanks your sample.
It is very useful for me.

the code is success running in iOS 7

when i update device to iOS8,
it can not jump to UIDocumentInteractionController.
(Maybe it can not get the most top view)

any one know what's happen?

very thanks

**Comment by tocute** [comment]
i trace code , and i find it.
[[UIApplication sharedApplication].keyWindow.subviews lastObject]

i always get uitransitionview , not uiview.
maybe it cause the UIDocumentInteractionController does not present

**Comment by tocute** [comment]
i think i find the problem.
it is different between ios 7/8 about uiview stack.
very thank

**Comment by sascha** [comment]
Is there even any point in using this in iOS 8.0? Don't they have their own share extension?
